### ISSUE TITLE
await?

### ISSUE THREAD

**Issue by ArneSchoonvliet** [ErazerBrecht/ErazerCQRS#5]
https://github.com/ErazerBrecht/ErazerCQRS/blob/5bc8e84392d73011fe3e007ef7e4b01db8eaa725/Erazer.DAL/ReadModel/Repositories/TicketEventRepository.cs#L28

**Comment by ErazerBrecht** [comment]
This method doesn't do anything after the insert. I wanted to avoid 'compiler garbage'

https://stackoverflow.com/a/38017167/2961887

**Comment by ErazerBrecht** [comment]
I have to admit it's not always the same which can make it strange.

await and async could be removed here:

https://github.com/ErazerBrecht/ErazerCQRS/blob/5bc8e84392d73011fe3e007ef7e4b01db8eaa725/Erazer.DAL/ReadModel/Repositories/TicketRepository.cs#L35

https://github.com/ErazerBrecht/ErazerCQRS/blob/5bc8e84392d73011fe3e007ef7e4b01db8eaa725/Erazer.DAL/ReadModel/Repositories/TicketRepository.cs#L40

**Comment by ArneSchoonvliet** [comment]
I learned something today
